---

- name: Cisco show version example
  hosts: FW
  gather_facts: false

  tasks:
    - name: run show version on the routers
      ios_command:
        commands: show version | incl up
      register: output

    - name: print output
      debug:
        var: output.stdout_lines

