---

- hosts: ar-n0-sw-01
  gather_facts: true
  connection: network_cli
  
  tasks:
    - name: show version
      cisco.ios.ios_command:
        commands:
          - show version
        host: "{{ ansible_host }}"
        username: artpsw
        password: ar09tp04!
        register: config

    - name: save output to /etc/ansible/backups 
      copy: 
        content: "{{ config.stdout[0] }}"
        dest: "/etc/ansible/backups/show_run_{{ inventory_hostname }}.txt"  
