---
- hosts: syslog-client
  become: yes
  tasks:
    - name: install apt syslog-ng fail2ban packages
      apt: 
        name: syslog-ng
        state: latest
        update_cache: yes
        cache_valid_time: 3600
    - name: install apt syslog-ng fail2ban packages
      apt:
        name: fail2ban
        state: latest
        update_cache: yes
        cache_valid_time: 3600
    - name: Restart service syslog-ng, in all cases
      service:
        name: syslog-ng
        state: restarted
    - name: Restart service fail2ban, in all cases
      service:
        name: fail2ban
        state: restarted

